services:
    db:
        image: mysql:8.0.33
        container_name: mysql-db
        restart: always
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${PORT_SQL}:3306"
        volumes:
            - "../project/db:/var/lib/mysql"
            - ./db/init.sql:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
            PMA_PORT: 3306
        ports:
            - 8080:80
 
    apache:
        build:
            context: ./httpd
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: apache-app
        restart: always
        volumes:
            - ../project/web:/var/www/html:cached
        ports:
            - 80:80
        depends_on:
            - php
    php:
        build:
            context: ./php
        container_name: php-app
        restart: always
        volumes:
            - ../project/web:/var/www/html:cached